<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @method User findOneBy(array $criteria, array $orderBy=null)
 */
class UserRepository extends ResourceRepository
{

    /**
     * @param $criteria
     *
     * @return User|false
     */
    public function findUserByUsernameOrEmail($criteria)
    {
        $builder = $this->createQueryBuilder('user');
        $expr    = $builder->expr();
        $orX     = $expr->orX();
        $orX->add($expr->eq('user.username', ':criteria'))
            ->add($expr->eq('user.email', ':criteria'));

        $result = $builder
            ->where($orX)
            ->setParameter('criteria', $criteria)
            ->setMaxResults(1)
            ->getQuery()
            ->getResult();

        return current($result);
    }
}
