imports:
    - { resource: parameters.yml }
    - { resource: services.yml }
    - { resource: security.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation:
        enabled: true
        enable_annotations: false
#        mapping:
#            paths:
#                - "%kernel.root_dir%/../src/AppBundle/Resources/config/validation"
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  ~ #session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - "bootstrap_3_layout.html.twig"
    globals:
        runtime: '@Components\Application\Runtime'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        default_repository_class: AppBundle\Repository\ResourceRepository
        mappings:
            AppBundle:
                type: yml

doctrine_migrations:
    dir_name: "%kernel.root_dir%/Migrations"
    namespace: Application\Migrations
    table_name: migrations
    name: Application Migrations
    organize_migrations: false

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

fos_oauth_server:
    db_driver:           orm
    client_class:        "%app.resource.api.client.class%"
    access_token_class:  "%app.resource.api.access_token.class%"
    refresh_token_class: "%app.resource.api.refresh_token.class%"
    auth_code_class:     "%app.resource.api.auth_code.class%"
    service:
        user_provider: app.manager.user

fos_rest:
    routing_loader:
        default_format: json                            # All responses should be JSON formated
        include_format: false                           # We do not include format in request, so that all responses
    serializer:
          serialize_null: true

    exception:
        enabled: true
        exception_controller: "fos_rest.exception.twig_controller:showAction"

    view:
        templating_formats:
            html: true
            js: true
        formats:
            jsonp: true
            json: true
            xml: true

    disable_csrf_role: ROLE_API_USER
    body_listener:
        decoders:
            json: fos_rest.decoder.jsontoform

jms_serializer:
    metadata:
        directories:
            data-access:
                namespace_prefix: "Components\\DataAccess"
                path: "@AppBundle/Resources/config/serializer/components/data-access"
            interactions:
                namespace_prefix: "Components\\Interaction"
                path: "@AppBundle/Resources/config/serializer/components/interaction"

knp_menu:
    # use "twig: false" to disable the Twig extension and the TwigRenderer
    twig:
        template: "@App/Partials/menu.html.twig"
    #  if true, enables the helper for PHP templates
    templating: false
    # the renderer to use, list is also available by default
    default_renderer: twig

app:
    email:
        address: noreply@restfully.org
        alias: RESTFully
    resources:
        user:
            model: AppBundle\Entity\User
            manager: AppBundle\Manager\UserManager
        project:
            model: AppBundle\Entity\Project
            controller: AppBundle\Controller\ProjectController
            manager: AppBundle\Manager\ProjectManager

        trans.unit:
            model: AppBundle\Entity\TransUnit
            controller: AppBundle\Controller\TransUnitController
            manager: AppBundle\Manager\TransUnitManager
        trans.value:
            model: AppBundle\Entity\TransValue
        api.client:
            model: AppBundle\Entity\Api\Client
        api.auth_code:
            model: AppBundle\Entity\Api\AuthCode
        api.access_token:
            model: AppBundle\Entity\Api\AccessToken
        api.refresh_token:
            model: AppBundle\Entity\Api\RefreshToken


