app_api_registration:
    prefix: /register
    resource: "registration.yml"

app_api_resetting:
    prefix: /reset
    resource: "resetting.yml"

app_api_profile:
    prefix: /profile
    resource: "profile.yml"