app_api_account:
    prefix: /account
    resource: "account.yml"

app_api_users:
    prefix: /users
    resource: "users.yml"
    defaults:
        resource: user

app_api_projects:
    prefix: /projects
    resource: "projects.yml"
    defaults:
        resource: project

app_api_statistics:
    prefix: /{project}/stats
    resource: "statistics.yml"

app_api_translations:
    prefix: /{project}/translations
    resource: "translations.yml"
    defaults:
        resource: "trans.unit"

app_api_environment:
    path: /environment
    defaults:
        _controller: AppBundle\Controller\HomeController:environmentAction
        _template: '@App/Home/environment.html.twig'

app_api_homepage_project:
    path:     /{project}
    defaults:
        _controller: AppBundle\Controller\HomeController:projectIndexAction
        _template: "@App/Home/project-index.html.twig"

app_api_homepage:
    path:     /
    defaults:
        _controller: AppBundle\Controller\HomeController:indexAction
        _template: "@App/Home/index.html.twig"