app_api_profile_index:
    path: /
    defaults:
        _controller: AppBundle\Controller\ProfileController:indexAction
        _template: "@App/Profile/index.html.twig"

app_api_profile_update:
    path: /
    methods: [PUT]
    defaults:
        _controller: AppBundle\Controller\ProfileController:updateAction
        _template: '@App/Profile/update.html.twig'
        _redirect: app_api_profile_index