app_api_projects_list:
    path: /
    defaults:
        _controller: app.controller.project:getCollectionAction

app_api_projects_create:
    path: /create
    defaults:
        _controller: app.controller.project:createAction
        _template: "@App/Project/create.html.twig"

app_api_projects_show:
    path: /{slug}
    defaults:
        _controller: app.controller.project:showAction
        _template: "@App/Project/show.html.twig"
app_api_projects_stats:
    path: /{slug}/stats
    defaults:
        _controller: app.controller.project:completionAction
        _template: "@App/Project/stats.html.twig"

app_api_projects_update:
    path: /{slug}/update
    defaults:
        _controller: app.controller.project:updateAction
        _template: "@App/Project/update.html.twig"