app_api_registration_index:
    path: /
    defaults:
        _controller: app.controller.registration:registerAction
        _template: "@App/Registration/register.html.twig"

app_api_registration_activate:
    path: /activate/{token}
    defaults:
        _controller: app.controller.registration:activateAction
        _template: "@App/Registration/activate.html.twig"
