app_registration:
    prefix: /register
    resource: "registration.yml"

app_resetting:
    prefix: /reset
    resource: "resetting.yml"

app_profile:
    prefix: /profile
    resource: "profile.yml"