app_translation_file:
    prefix: /file
    resource: "translations/file.yml"

app_translations_translate:
    prefix: /translate
    resource: "translations/translate.yml"

app_translations_list:
    path: /
    defaults:
        _controller: app.controller.trans.unit:indexAction
        _template: "@App/TransUnit/index.html.twig"

app_translations_create:
    path: /create
    defaults:
        _controller: app.controller.trans.unit:createAction
        _template: "@App/TransUnit/create.html.twig"

app_translations_update:
    path: /{slug}/update
    defaults:
        _controller: app.controller.trans.unit:updateAction
        _template: "@App/TransUnit/update.html.twig"

