AppBundle\Entity\Project:
    type: entity
    table: project
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY

    fields:
        canonical:
            type: string
            nullable: false
            unique: true
            gedmo:
                slug:
                    fields:  [name]
                    updatable: false
        name:
            type: string
            nullable: false
        description:
            type: text
            nullable: true

