AppBundle\Entity\TransValue:
    type: entity
    table: trans_value
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        locale:
            type: string
            nullable: false

        content:
            type: text
            nullable: true
    manyToOne:
        unit:
            targetEntity: AppBundle\Entity\TransUnit
            inversedBy: translations
            cascade: [all]