AppBundle\Entity\TransValue:
    type: entity
    table: trans_value
    indexes:
        idx_locale: { columns: [locale] }
        idx_state: { columns: [state] }
        ics_locale_state: { columns: [locale, state] }
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        locale:
            type: string
            nullable: false
            length: 10

        content:
            type: text
            nullable: true

        state:
            type: string
            nullable: true
            length: 50

    manyToOne:
        unit:
            targetEntity: AppBundle\Entity\TransUnit
            inversedBy: translations
            cascade: [all]