AppBundle\Entity\User:
    type: entity
    table: user
    repositoryClass: AppBundle\Repository\UserRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            scale: 0
            length: 255
            unique: true
            nullable: false
            precision: 0
        email:
            type: string
            scale: 0
            length: 255
            unique: true
            nullable: false
            precision: 0
        password:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        isActive:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: is_active
        roles:
            type: json_array
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        token:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
    lifecycleCallbacks: {  }
    oneToOne:
        profile:
            targetEntity: AppBundle\Entity\Profile
            mappedBy: user
            cascade: [ all ]
