services:
    Components\Localization\ILocalizer: '@app.localizer'
    Components\Infrastructure\ICommandBus: '@app.command_bus.logging'
    Components\Resource\IManager: '@AppBundle\Manager\ResourceManager'
    AppBundle\Controller\SecurityController: '@app.controller.security'
    AppBundle\Controller\RegistrationController:  '@app.controller.registration'
    AppBundle\Controller\ResetController: '@app.controller.resetting'
    Components\Infrastructure\Presentation\IPresenter: '@AppBundle\Presentation\ViewHandlerPresenter'
    AppBundle\Presentation\TwigPresenter: '@app.presenter.twig'
    AppBundle\Presentation\JsonPresenter: '@app.presenter.json'
    AppBundle\Presentation\ViewHandlerPresenter: '@app.presenter.view'
    Components\Resource\ITransUnitManager: '@app.manager.trans.unit'
    FOS\RestBundle\View\ViewHandler: '@fos_rest.view_handler'
    AppBundle\Controller\TransUnitController: '@app.controller.trans.unit'
    AppBundle\Controller\FileController: "@app.controller.file"
    AppBundle\Controller\TranslateController: '@app.controller.translate'


