services:
    app.handler.resource:
        class: Components\Interaction\Resource\ResourceHandler

    app.handler.create_resource:
        class: Components\Interaction\Resource\CreateResource\CreateResourceHandler
        parent: app.handler.resource
        tags:
            - { name: app.command.handler }

    app.handler.users.reset_password:
        class: Components\Interaction\Users\ResetPassword\ResetPasswordHandler
        arguments:
            - "@app.notifier"
        tags:
            - { name: app.command.handler }

    app.handler.users.change_password:
        class: Components\Interaction\Users\ChangePassword\ChangePasswordHandler
        arguments:
            - "@app.notifier"
        tags:
            - { name: app.command.handler }

    app.handler.users.register:
        class: Components\Interaction\Users\Register\RegisterHandler
        arguments:
            - "@app.notifier"
        tags:
            - { name: app.command.handler }

    app.handler.translation.load_file:
        class: Components\Interaction\Translations\LoadFile\LoadFileHandler
        arguments:
            - "@app.localization.message_loader"
        tags:
            - { name: app.command.handler }

    app.handler.translation.import_catalogue:
        class: Components\Interaction\Translations\ImportCatalogue\ImportCatalogueHandler
        arguments:
            - "@app.manager.trans.unit"
            - "@app.manager.project"
        tags:
            - { name: app.command.handler }

    app.handler.translation.export_catalogue:
        class: Components\Interaction\Translations\ExportCatalogue\ExportCatalogueHandler
        arguments:
            - "@app.localization.message_writer"
            - "@app.manager.trans.unit"
        tags:
            - { name: app.command.handler }

    app.handler.statistics.overview:
        class: Components\Interaction\Statistics\GetOverview\GetOverviewHandler
        arguments:
            - "@app.manager.trans.unit"
        tags:
            - { name: app.command.handler }

    app.handler.statistics.completion:
        class: Components\Interaction\Statistics\GetCompletion\GetCompletionHandler
        arguments:
            - "@app.manager.trans.unit"
        tags:
            - { name: app.command.handler }

    app.handler.environment:
        class: Components\Interaction\Environment\GetEnvironmentHandler
        arguments:
            - "@app.manager.project"
            - "@app.manager.trans.unit"
        tags:
            - { name: app.command.handler }