services:

    app.presenter.twig:
        class: AppBundle\Presentation\TwigPresenter
        arguments:
            - "@twig"

    app.presenter.view:
        class: AppBundle\Presentation\ViewHandlerPresenter
        arguments:
            - "@fos_rest.view_handler"

    app.presenter.json:
        class: AppBundle\Presentation\JsonPresenter
        arguments:
            - "@serializer"

    app.presenter: '@app.presenter.json'

    app.flash:
        class: AppBundle\Presentation\ResultFlashBuilder
        arguments:
            - "@session.flash_bag"
            - "@translator"